### ISSUE TITLE
Error during entering nvim from current folder

### ISSUE THREAD

**Issue by farukara** [nvim-tree/nvim-tree.lua#1883] opened 2023-01-04 11:51 UTC
### Description

when I start nvim with current folder I started to get the following error. I was not getting this one before. Updating something should cause it but I could not find out.
cmd:
$nvim .

output when nvim is opened:

`Error executing vim.schedule lua callback: ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:60: Invalid window id: 10
08
stack traceback:
        [C]: in function 'nvim_win_get_cursor'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:60: in function 'draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:117: in function 'open_view_and_draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:163: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:278: in function 'on_enter'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:862: in function <...m/site/pack/packer/start/nvim-tree.lua/
lua/nvim-tree.lua:861>`

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.6.2

### nvim-tree version

bac962c

### Minimal config

```lua
defaults
```

### Steps to reproduce

nvim .

### Expected behavior

nvim should open with nvim-tree tab on the left

### Actual behavior

nvim-tree does not open and I got error that I wrote above

**Comment by gleydson404** [comment] 2023-01-04 14:49
I had the same issue this week. 

I had to uninstall luvarVim, uninstall neoVim, install neovim, install lunarVim to get it working again.

**Comment by alex-courtis** [comment] 2023-01-07 01:27
This is very concerning. It sounds like there may be a race condition around startup automation.

I understand that you are using nvim-tree defaults. Are you using any plugins / automation at nvim startup?

Please attempt to reproduce and provide a minimal config `nvt-min.lua` : https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by nbili** [comment] 2023-01-18 15:44
@farukara I encountered a similar problem and was able to resolve it by disabling the [`hijack_directories.auto_open`](https://github.com/nvim-tree/nvim-tree.lua/blob/e8a89db1bbc06510a76fc935754b4e99a3e5e8a7/doc/nvim-tree-lua.txt#L283) option. This eliminated a race condition that was occurring during startup automation. In my scenario, the problem is caused by a race condition with another plugin `telescope-file-browser.nvim`.

**Comment by alex-courtis** [comment] 2023-01-21 00:14
> In my scenario, the problem is caused by a race condition with another plugin `telescope-file-browser.nvim`.

This is not uncommon. #1669

**Comment by alex-courtis** [comment] 2023-01-21 05:34
Closing, to follow up in #1669

**Closed by alex-courtis** 2023-01-21 05:34 UTC
Labels: bug, awaiting feedback
