### ISSUE TITLE
Case sensitive rename not possible (cannot rename)

### ISSUE THREAD

**Issue by justb3a** [nvim-tree/nvim-tree.lua#914] opened 2022-01-24 09:54 UTC
**OS**
macOS Monterey 12.1

**Neovim version**
v0.6.1

**Nvim-tree version**
`master`

**Describe the bug**
Renaming a file like `Something.md` to `something.md` does not work. **[NvimTree] Cannot rename: file already exists** If I rename it first to something different, it works: `Something.md` → `something2.md`  → `something.md` .

**Expected behavior**
Renaming a file respecting lower and upper case is possible. `Something.md` → `something.md`.

Thanks for your work 🙏🏻

**Comment by kyazdani42** [comment] 2022-02-03 12:25
Hum hum, i think this is an issue with macos which i believe doesn't make any difference between upper and lower cases. 
see https://discussions.apple.com/thread/251191099.
Take care about that, i know people that had very weird behaviors in their codebases with macos because of this :smile:

**Comment by gegoune** [comment] 2022-02-03 12:49
That is correct. Exactly same behaviour can be observed in terminal emulator. There is nothing nvim-tree can or should do about it.

**Comment by martin-braun** [comment] 2023-02-02 23:35
@kyazdani42 @gegoune Please reopen. While it is true that MacOS won't allow the same file/folder with different casing in the same directory, it should still be possible to rename the file without the given error.

`touch File.txt && mv File.txt file.txt` works, so should `nvim-tree`.

**Comment by gegoune** [comment] 2023-02-03 01:44
```sh
bash-5.2$ touch File.txt && mv File.txt file.txt
mv: 'File.txt' and 'file.txt' are the same file
```

**Comment by martin-braun** [comment] 2023-02-03 01:58
@gegoune Not sure where you test, but macOS is still on bash3.2 and it works:

```bash
bash-3.2$ touch File.txt && mv File.txt file.txt
bash-3.2$
```

**Comment by gegoune** [comment] 2023-02-03 10:54
```sh
$ /bin/bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ touch File.txt && mv File.txt file.txt
mv: 'File.txt' and 'file.txt' are the same file
bash-3.2$
```

Did you perhaps format your FS with support for case sensitivity?
https://support.apple.com/lt-lt/guide/disk-utility/dsku19ed921c/mac

@alex-courtis Are we preventing such move within nvim-tree?

**Comment by alex-courtis** [comment] 2023-02-04 04:33
> Are we preventing such move within nvim-tree?

We aren't doing anything special; we are just passing the user's input directly to `:h uv.fs_rename()`

**Comment by martin-braun** [comment] 2023-02-04 15:55
@gegoune This is APFS and it's not case-sensitive: 

![Screen Shot 2023-02-04 at 4 52 46 PM](https://user-images.githubusercontent.com/24259245/216776966-b46426bb-5ff2-4f37-821d-ab4aa6b2d89c.png)

My default shell is `zsh`, but whatever shell I use, `touch File.txt && mv File.txt file.txt` works. Also renaming `file.txt` to `File.txt` doesn't cause any errors in Finder, so I expect `nvim-tree` to behave identical. 

![2023-02-04 4 54 47 PM](https://user-images.githubusercontent.com/24259245/216777061-90a4d1f0-9f4a-492b-9a60-09157f289bd5.gif)

**Comment by alex-courtis** [comment] 2023-02-05 01:51
Thanks for raising the issue with libuv @martin-braun 

For posterity's sake: `:lua vim.loop.fs_rename('y.c', 'Y.c')` was successful on linux. Does that fail on macOS?

It _could_ be an issue between vim and its libuv implementation.

**Comment by gegoune** [comment] 2023-02-05 10:44
Interestingly it works on MacOS too, while by principle it shouldn't I think. By default AFPS are case insensitive.

**Comment by martin-braun** [comment] 2023-02-05 19:48
@alex-courtis Thanks a lot for showing me how to invoke it directly. As you probably have seen they cannot reproduce the issue and I can confirm this. Running `:lua vim.loop.fs_rename('file.txt', 'File.txt')` works, so there is probably a wrong check in the implementation. Are you sure you are calling `uv.fs_rename()` directly without any further checks?

@gegoune In principle it should work. The file system is smart enough to understand that the file that is about to be renamed cannot block the new file.

**Comment by alex-courtis** [comment] 2023-02-05 23:33
My apologies, I did not look deep enough; there is an additional check prior to the rename process:

`vim.loop.fs_stat(path)`

It's also using libuv so I will be suprised if it functions differently.

What does the following show?
```lua
:lua print(vim.inspect(vim.loop.fs_stat('/full/path/to/File.txt')))
```

**Comment by martin-braun** [comment] 2023-02-05 23:48
@alex-courtis Both commands output: 

```
{
  atime = {
    nsec = 982334749,
    sec = 1675640190
  },
  birthtime = {
    nsec = 982334749,
    sec = 1675640190
  },
  blksize = 4096,
  blocks = 0,
  ctime = {
    nsec = 982334749,
    sec = 1675640190
  },
  dev = 16777221,
  flags = 0,
  gen = 0,
  gid = 20,
  ino = 153513803,
  mode = 33188,
  mtime = {
    nsec = 982334749,
    sec = 1675640190
  },
  nlink = 1,
  rdev = 0,
  size = 0,
  type = "file",
  uid = 501
}
```

Although only `file.txt` exists. Of course it routes to the same file, because the MacOS' file system is case-insensitive. However, `:lua vim.loop.fs_rename('file.txt', 'File.txt')` still works, because in the attempt to rename the file the APFS is smart enough to handle this case.

Can't you just attempt to rename the file without prior check and handle/catch the error instead?

**Comment by alex-courtis** [comment] 2023-02-06 01:42
> Can't you just attempt to rename the file without prior check and handle/catch the error instead?

That's an excellent idea! Unfortunately `fs_rename` simply clobbers the target.

Let's try an alternate approach: `:lua print(vim.loop.fs_open('/path/to/File.txt', 'r', 438)`

An option may simply be to remove the check; UNIX renames clobber and that is reasonable behaviour.

**Comment by gegoune** [comment] 2023-02-06 10:26
After bit more of investigation I found `mv` from `coreutils` to be a culprit. `mv` shipped with MacOS behaves as @martin-braun describes.

I am in for removing that check.

**Comment by martin-braun** [comment] 2023-02-06 10:39
@alex-courtis The command works, prints the handle, i.e. `34`.

I can confirm that `mv` is clobbering by default. Enabling clobbering by default seems reasonable, however an option flag for the `setup` function might be suitable to toggle the behavior.

Btw, I also tested the folder scenario (case-renaming and clobbering). Case-renaming on folders is the same like on files and clobbering can't happen. `mv` will move one folder into another instead, while `vim.loop.fs_rename` will silently fail the operation.

It should be natural outcome to remove the check.

**Comment by alex-courtis** [comment] 2023-02-07 00:00
We have some inconsistent results here: `fs_open` and `fs_stat` differ.

`fs_open` is a very heavy operation, requiring close etc.

`fs_rename` appears to directly invoke rename(2) https://docs.libuv.org/en/v1.x/fs.html

**Proposal:** remove the check and just invoke `fs_rename`. The OS can do whatever it can, which seems to be sensible for macOS. An informative error will be returned on failure. Are you OK with that @gegoune ?

**Comment by alex-courtis** [comment] 2023-02-11 03:51
> * Please do not clobber on create, because it will make the creation of a file a destructive operation with potential data loss. Alternatively, maybe it is better to implement `touch` instead?

I like that!

**Comment by alex-courtis** [comment] 2023-02-11 04:02
The no-check-and-clobber approach has created more problems than it solves:
* unwelcome create clobbering
* issues with rename buffers

File existence checks were the root cause; if they were functioning correctly everything else would work as expected, including all the rename prompts.

Simpler solution:
* existence checks use fs_stat on linux, fs_open/close on other OS
* fix the "both files open" paste/rename failure  https://github.com/nvim-tree/nvim-tree.lua/pull/1977#issuecomment-1420072224

**Comment by alex-courtis** [comment] 2023-02-12 00:18
@martin-braun please test this simple fix, which is current functionality with a fixed existence check.

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 914-fix-file-existence-check
```

**Comment by martin-braun** [comment] 2023-02-12 00:55
@alex-courtis hm, I'm on branch `914-fix-file-existence-check`, there are still some issues: 

- Copying or cutting `File.txt` to a different directory with a `file.txt` will still ask to overwrite a "`File.txt`" instead of "`file.txt`"
- Overwriting `file.txt` with `File.txt` will rename the pasted file to `file.txt`, but it should remain its origin name `File.txt`
- Renaming `file.txt` to `File.txt` is not possible anymore, "file already exists`
- Having both buffers open, copy/paste seems not to complain anymore, but cut/paste still does: 

```
E5108: Error executing lua: ...te/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/utils.lua:166: Failed to rename buffer
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...te/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/utils.lua:166: in function 'rename_loaded_buffers'
        ...pt/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:193: in function 'action_fn'
        ...pt/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:89: in function 'on_process'
        ...pt/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:102: in function 'callback'
        ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:148: in function 'on_confirm'
        ...al/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/ui.lua:93: in function 'input'
        ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:147: in function 'prompt'
        ...pt/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:99: in function 'do_single_paste'
        ...pt/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:170: in function 'handle_tree_actions'
        ...ker/opt/nvim-tree.lua/lua/nvim-tree/actions/dispatch.lua:123: in function 'dispatch'
        .../packer/opt/nvim-tree.lua/lua/nvim-tree/actions/init.lua:273: in function <.../packer/opt/nvim-tree.lua/lua/nvim-tree/acti
ons/init.lua:272>
```

It somehow got worse.

> Whilst you are in a testing mood can you please test `:NvimTreeFindFile`for `File.txt` and `file.txt`

`:NvimTreeFindFile` works on both, `File.txt` and `file.txt`.

**Comment by alex-courtis** [comment] 2023-02-12 01:52
> * Copying or cutting `File.txt` to a different directory with a `file.txt` will still ask to overwrite a "`File.txt`" instead of "`file.txt`"
> 
> * Overwriting `file.txt` with `File.txt` will rename the pasted file to `file.txt`, but it should remain its origin name `File.txt`

Ah... I haven't fixed that yet...

> * Having both buffers open, copy/paste seems not to complain anymore, but cut/paste still does:

That one's an existing bug and still needs fixing. Tracking separately: #1989

> :NvimTreeFindFile works on both, File.txt and file.txt.

Thank you.

> * Renaming file.txt to File.txt is not possible anymore, "file already exists`

This is a problem. Unfortunately we have a poor dev loop as I can't test anything...

I'm going to have to ask you to do some digging:
* enable [dev logging](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#diagnostic-logging)
* open the test lua file in a regular vim session
* fill in `PATH`
* execute with `:so`
  * only `file.txt` exists
  * only `File.txt` exists
  * both exist

[914.lua.gz](https://github.com/nvim-tree/nvim-tree.lua/files/10715096/914.lua.gz)

**Comment by martin-braun** [comment] 2023-02-12 13:57
Thanks @alex-courtis for keeping on, I'm happy to help to diagnose the problem further. I added 

```
log = {
  enable = true,
  truncate = true,
  types = {
    diagnostics = true,
    git = true,
    profile = true,
    watcher = true,
  },
},
```

to my options. `nvim-tree.log` is created, but no entries are added when running `:so 914.lua`.

> both exist

Won't be possible, since `file.txt` and `File.txt` can't coexist in the same directory, since this is a case-insensitive file system.

**Comment by alex-courtis** [comment] 2023-02-12 23:42
> to my options. `nvim-tree.log` is created, but no entries are added when running `:so 914.lua`.

My apologies; I didn't specify... you'll need to set `log.types.dev`

To keep things readable you can disable the other types.

> > both exist
> 
> 
> Won't be possible, since `file.txt` and `File.txt` can't coexist in the same directory, since this is a case-insensitive file system.

Whoops... didn't remember that one. The single files will give us all the info we need.

**Comment by alex-courtis** [comment] 2023-02-13 03:17
I've added a couple more tests; hopefully we can get a solution after this.

[914.2.lua.gz](https://github.com/nvim-tree/nvim-tree.lua/files/10718297/914.2.lua.gz)

**Comment by martin-braun** [comment] 2023-02-13 15:28
@alex-courtis here we go.

<img width="163" alt="Screen Shot 2023-02-13 at 4 25 00 PM" src="https://user-images.githubusercontent.com/24259245/218499212-17b5b95a-3eeb-4605-a2a3-a7364422d531.png">

`:so 914.2.lua` (`local PATH="/Users/marty/Downloads/vimtt/lower"`)

```
[2023-02-13 16:23:46] [dev] 
[2023-02-13 16:23:46] [dev] ---
[2023-02-13 16:23:46] [dev] has unix: 1
[2023-02-13 16:23:46] [dev] has mac: 1
[2023-02-13 16:23:46] [dev] has macunix: 1
[2023-02-13 16:23:46] [dev] 
[2023-02-13 16:23:46] [dev] testing /Users/marty/Downloads/vimtt/lower/file.txt
[2023-02-13 16:23:46] [dev] fs_stat: table: 0x01070ee650
[2023-02-13 16:23:46] [dev] fs_open  0: 38
[2023-02-13 16:23:46] [dev] fs_close 0: true
[2023-02-13 16:23:46] [dev] fs_open  438: 38
[2023-02-13 16:23:46] [dev] fs_close 438: true
[2023-02-13 16:23:46] [dev] utils.file_exists: true
[2023-02-13 16:23:46] [dev] filereadable: 1
[2023-02-13 16:23:46] [dev] getftype: file
[2023-02-13 16:23:46] [dev] readfile: true 1
[2023-02-13 16:23:46] [dev] 
[2023-02-13 16:23:46] [dev] testing /Users/marty/Downloads/vimtt/lower/File.txt
[2023-02-13 16:23:46] [dev] fs_stat: table: 0x0106b9a228
[2023-02-13 16:23:46] [dev] fs_open  0: 38
[2023-02-13 16:23:46] [dev] fs_close 0: true
[2023-02-13 16:23:46] [dev] fs_open  438: 38
[2023-02-13 16:23:46] [dev] fs_close 438: true
[2023-02-13 16:23:46] [dev] utils.file_exists: true
[2023-02-13 16:23:46] [dev] filereadable: 1
[2023-02-13 16:23:46] [dev] getftype: file
[2023-02-13 16:23:46] [dev] readfile: true 1
```

`:so 914.2.lua` (`local PATH="/Users/marty/Downloads/vimtt/upper"`)

```
[2023-02-13 16:25:37] [dev] 
[2023-02-13 16:25:37] [dev] ---
[2023-02-13 16:25:37] [dev] has unix: 1
[2023-02-13 16:25:37] [dev] has mac: 1
[2023-02-13 16:25:37] [dev] has macunix: 1
[2023-02-13 16:25:37] [dev] 
[2023-02-13 16:25:37] [dev] testing /Users/marty/Downloads/vimtt/upper/file.txt
[2023-02-13 16:25:37] [dev] fs_stat: table: 0x01067956e0
[2023-02-13 16:25:37] [dev] fs_open  0: 40
[2023-02-13 16:25:37] [dev] fs_close 0: true
[2023-02-13 16:25:37] [dev] fs_open  438: 40
[2023-02-13 16:25:37] [dev] fs_close 438: true
[2023-02-13 16:25:37] [dev] utils.file_exists: true
[2023-02-13 16:25:37] [dev] filereadable: 1
[2023-02-13 16:25:37] [dev] getftype: file
[2023-02-13 16:25:37] [dev] readfile: true 1
[2023-02-13 16:25:37] [dev] 
[2023-02-13 16:25:37] [dev] testing /Users/marty/Downloads/vimtt/upper/File.txt
[2023-02-13 16:25:37] [dev] fs_stat: table: 0x0106b4bdc8
[2023-02-13 16:25:37] [dev] fs_open  0: 40
[2023-02-13 16:25:37] [dev] fs_close 0: true
[2023-02-13 16:25:37] [dev] fs_open  438: 40
[2023-02-13 16:25:37] [dev] fs_close 438: true
[2023-02-13 16:25:37] [dev] utils.file_exists: true
[2023-02-13 16:25:37] [dev] filereadable: 1
[2023-02-13 16:25:37] [dev] getftype: file
[2023-02-13 16:25:37] [dev] readfile: true 1
```

**Comment by alex-courtis** [comment] 2023-02-13 22:01
> ```
> 
> ```
> 
> 
>     
>   
> 
> It seems there is no way to make a case-sensitive check on the default APFS. Why did the initial attempt failed? It was working, just causing issues with the buffers. Also it was clobbering on create, which could be prevented by the case-insensitive check, like it does now. It really seemed so trivial to just disable the check on move/paste, but it turned out to be a bigger challenge than anticipated.

It does seem that nvim really cannot see the difference.

Possible solution: delete the existing target file and its buffer first, then copy/rename.

**Comment by alex-courtis** [comment] 2023-02-14 02:40
Let's try that again:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 914-allow-rename-overwrite
```

@martin-braun I'd be grateful if you tested:
* rename
  * file.txt -> File.txt
  * File.txt -> file.txt
  * file.txt -> File.txt overwrite
  * file open and visible in a window
  * file open but not visible
  * file not open
* copy paste
  * same tests as above
* cut paste
  * same tests as above

**Comment by alex-courtis** [comment] 2023-02-19 23:21
/nudge @martin-braun 

I would be most grateful if you could test the above fix.

**Comment by alex-courtis** [comment] 2023-02-20 23:49
This is a real problem. Thank you for testing the separate directories, that's something I did not consider.

I'm not sure that we can find a fix for this; any solutions are fragile/broken and introduce new problems.

Pragmatic actions:
1. Do nothing, list this limitation in `:help nvim-tree-os-specific`
2. Implement delete/rename
3. Remove or fix functionality to open the new buffer, #1989

I'm tempted to go with just 2 and resolve 3 at another time. @gegoune ?

**Comment by alex-courtis** [comment] 2023-03-04 03:59
I'm afraid that we cannot realistically achieve this.

It's a situation that neovim/luajit/libuv cannot deal with. Any fixes we attempt are hacky workarounds that introduce too many potential issues.

This is not a vim specific issue either; some of my colleagues use macOS and they often have strange dramas with git and case sensitivity.

Pragmatic workarounds:
* use a case sensitive file system
* rename the file via the terminal if possible

Documenting limitation.

**Closed by alex-courtis** 2023-03-04 03:59 UTC
Labels: bug, OS macOS

**Comment by Fadarrizz** [comment] 2023-04-04 15:25
Bummer that it cannot be fixed right now. 

In case for an alternative, it is possible to rename in Netrw `:Ex`.

**Comment by alex-courtis** [comment] 2023-04-06 22:56
> If anyone looking for an alternative, it is possible to rename in Netrw `:Ex`.

That's useful, thank you.

**Comment by fizbik** [comment] 2023-11-03 20:19
Another workaround if you're too lazy to leave neo-tree like me:

app.jsx -> app.jsx**2** -> **A**pp.jsx
