### ISSUE TITLE
Keep cursor at highlighted file/directory when clearing filter

### ISSUE THREAD

**Issue by stickperson** [nvim-tree/nvim-tree.lua#1999] opened 2023-02-15 12:55 UTC
**Is this a question?**
No

**Can this functionality be implemented utilising API?**
Possibly. `api.tree.get_node_under_cursor` can get the node but there does not appear to be a method to navigate back to it.

**Is your feature request related to a problem? Please describe.**
When clearing a filter, it's desirable to keep the node on the current folder/file as opposed to the line.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
N/A

**Additional context**
`nvim-tree.renderer.draw()` is called when clearing the filter. [This](https://github.com/nvim-tree/nvim-tree.lua/blob/b712b82b0ca4eb402ced2d83f8082366989e43e0/lua/nvim-tree/renderer/init.lua#L90) is where the cursor position is set.

https://user-images.githubusercontent.com/3304073/219032996-d3b253fc-d4eb-43ed-8140-3a628786bb19.mov

**Comment by alex-courtis** [comment] 2023-02-18 01:09
Duplicate of #1785

**Closed by alex-courtis** 2023-02-18 01:09 UTC
Labels: feature request
