### ISSUE TITLE
Too much `OptionSet`, `TextChanged`, `CursorMoved` triggered when `nvim-tree` opened.

### ISSUE THREAD

**Issue by peter-lyr** [nvim-tree/nvim-tree.lua#2332] opened 2023-07-21 01:45 UTC
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/55801796/0ff5b738-1f6a-46e0-b1bc-328f240123f8)
Above picture shows the problem I met.
I had only 4 plugins loaded:
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/55801796/b5db90af-cc4a-4c7b-8224-ab69073b97ef)
It's consuming excessive CPU resources when nvim-tree opened. How can I ignore those Events properly.
Thanks.

**Comment by gegoune** [comment] 2023-07-21 07:11
Please provide reproducible configuration and steps as per https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication.

**Comment by alex-courtis** [comment] 2023-07-22 07:21
> But I can reproduce the problem on `lazy.nvim` when I open `nvim-qt.exe`.

Are there any plugins other than nvim-tree running under that configuration? If so it's likely that they are be the cause.

My opinion:

Lazy solves a problem that doesn't exist, but adds a great deal of complexity (actual plugin loading) as well as configuration complexity.

Perhaps you might profile startup time / load with lazy running and with a regular, eager plugin manager. If there is an order of magnitude or two difference AND lazy loading doesn't affect your experience at runtime with pauses etc., then you might have a case for lazy.

I've never received an answer when asking a lazy user to profile their startup with/without lazy.

**Comment by gegoune** [comment] 2023-07-22 08:08
I am going to close this issue now. It's not reproducible without additional plugins. If there is conflict between nvim-tree and some other conflict there might be something actionable by us, otherwise there isn't much we can do.

You could check what auto commands are firing and see where they are coming from. That should help narrowing the issue.

(We could improve minimal config, especially use of `NVIM_APPNAME`, see https://github.com/NeogitOrg/neogit/issues/621 for some details.)

**Closed by gegoune** 2023-07-22 08:08 UTC

**Comment by peter-lyr** [comment] 2023-07-22 14:45
https://github.com/nvim-tree/nvim-tree.lua/assets/55801796/ffe9c6f8-62fa-4a7a-9183-9ccf24c665a2

I reproduce this problem maybe in `packer.nvim`.

Here is my new computer, there is only one folder in my `Desktop` containing `nvim-win64` and `nvt-min\nvt-min.lua`:

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=C:\Users\llydr\Desktop\nv\nvt-min\site]]
local package_root = [[C:\Users\llydr\Desktop\nv\nvt-min\site\pack]]
local install_path = package_root .. [[\packer\start\packer.nvim]]
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
  local file = [[C:\Users\llydr\Desktop\nv\nvt-min\nvt-min.log]]
  pcall(vim.api.nvim_del_autocmd, vim.g.test_au1)
  vim.g.test_au1 = vim.api.nvim_create_autocmd({
    "CursorMoved",
    "TextChanged",
    "OptionSet",
  }, {
    callback = function(ev)
      vim.fn.writefile({ string.format([[%-3.3f %-2d %-20s - "%s"]], os.clock(), ev.buf, ev.event, ev.file) }, file, 'a')
    end,
  })
end
```

`OptionSet` is not always triggered. It seems to have something to do with git, but I'm not sure.

Thanks!

**Comment by gegoune** [comment] 2023-07-22 17:31
Your video doesn't load for me. Also they are not very helpful in the first place anyway, we are not sure what you are trying to show, reproducible steps are way better, but you failed to provide them twice. You have also choose not to provide all other essential information as per our bug reporting form (https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml); that, and the fact that neither of us has access to Windows machine makes it impossible to try to help with your issue. Please open new issue, with all required information filled in, but instead of using configuration file from bug report form please us this snippet (put it into `nvt-min.lua` instead):

```lua
for name, url in pairs {
  tree = 'https://github.com/nvim-tree/nvim-tree.lua.git',
  devicons = 'https://github.com/nvim-tree/nvim-web-devicons.git',
} do
  local install_path = vim.fn.fnamemodify('/tmp/nvim_issue/' .. name, ':p')  -- TODO: Please change the path here!!! 
  if vim.fn.isdirectory(install_path) == 0 then vim.fn.system { 'git', 'clone', '--depth=1', url, install_path } end
  vim.opt.runtimepath:append(install_path)
end

vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require('nvim-tree').setup()
print 'Minimal Config Ready!'
```

Please pay attention to line with `install_path`, you will need to change it so it works on Windows.

**Comment by alex-courtis** [comment] 2023-07-23 06:42
> (We could improve minimal config, especially use of `NVIM_APPNAME`, see [NeogitOrg/neogit#621](https://github.com/NeogitOrg/neogit/issues/621) for some details.)

Nice... it sounds like it's time. The packer auto load is sometimes quite problematic.

I've had to stray quite far from the minimal configuration for my dev/replication setup: https://github.com/alex-courtis/arch/blob/02507049a79a230febbf4aa9c0ff73deb1331bf5/config/nvim/nvt-dev-template.lua
