### ISSUE TITLE
Getting error when calling Lspsaga peek_definition

### ISSUE THREAD

**Issue by wr9dg17** [nvim-tree/nvim-tree.lua#2101] opened 2023-03-31 15:44 UTC
### Description

When I start neovim first time and call `Lspsaga peek_definition()` in any part of the code, an error appears, after pressing any key (to close the error), the `peek_definition` modal window appears. Subsequent calls to `peek_definition` do not raise this error.

`
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'startswith'
        ...ker/start/nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:21: in function 'is_folder_ignored'
        ...ker/start/nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:47: in function 'create_watcher'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:20: in function 'new'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/core.lua:19: in function 'init'
        .../nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:70: in function 'f'
        .../nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:60: in function 'force_dirchange'
        .../nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:46: in function 'fn'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:45: in function 'change_root'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:143: in function 'find_file'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:477: in function 'callback'
        .../pack/packer/start/nvim-tree.lua/lua/nvim-tree/utils.lua:331: in function <.../pack/packer/start/nvim-tree.lua/lua/nvim-tree/utils.lua:330>
`

https://user-images.githubusercontent.com/19671564/229167602-4c0c82a1-18c0-4f0b-9788-2a7acb23dfcd.mov

### Neovim version

```text
NVIM 0.8.6
```

### Operating system and version

macOS Ventura 13.2

### nvim-tree version

nightly

### Minimal config

```lua
all default config from docs
```

### Steps to reproduce

1. open any project
2. move to any code and call Lspsaga peek_definition

**Comment by alex-courtis** [comment] 2023-04-03 03:12
@wr9dg17 it sounds like we might have a race condition with temporary files being created.

Please produce a [Clean Room Replicator](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) with `Lspsaga` and instructions on how to reproduce the problem.

Please be mindful that I'm not familiar with Lspsaga; an explanation of exactly what you are doing and the expected results would be gratefully appreciated.

**Comment by alex-courtis** [comment] 2023-04-03 05:54
What's the reason for closing this one @wr9dg17 ?

You have uncovered a real bug that should be addressed.

**Comment by wr9dg17** [comment] 2023-04-03 06:15
@alex-courtis I had trouble to replicate [Clean Room](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication)

P.S.I have little experience with neovim 😶

**Comment by alex-courtis** [comment] 2023-04-06 22:53
> I was not able to configure the options such as event and opt for lspsaga provided by the use() function.

I'll see if we can make other plugin's config in packer more available.

> But the strangest thing is that after returning the options to the original ones and removing the [nvim-barbecue](https://github.com/utilyre/barbecue.nvim) plugin, such an error no longer occurred smile

That can happen; simple things like load order can affect behaviour.

> I'm sorry I couldn't help you find the problem I spent many hours on this.

Thank you for taking the time. Please do raise an issue if you experience further problems and can reproduce.

**Closed by alex-courtis** 2023-04-06 22:53 UTC
Labels: bug, awaiting feedback
