### ISSUE TITLE
highlight_opened_files doesn't work - despite I've also refreshed with :NvimTreeRefresh

### ISSUE THREAD

**Issue by matteouni** [nvim-tree/nvim-tree.lua#1779] opened 2022-11-27 16:33 UTC
### Description

when I open a file from nvim_tree's window, I do not see any highlighted name, nor I see the highlighted name of the file where I'm currentrly working on. 

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by xubuntu0@xubuntu0

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux xubuntu0 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### nvim-tree version

b17358f

### Minimal config

```lua
require('packer').startup(function(use)
    use "nvim-tree/nvim-tree.lua"
    use "nvim-treesitter/nvim-treesitter"
    use "wbthomason/packer.nvim"
end)

require("nvim-treesitter.configs").setup({
    ensure_installed = {"lua"}, --parsers
    indent = {enable = true},
    highlight = {enable = true}, --"I get query error: invalid node type at position" paragraph. Syntax highlighting 
})
require("nvim-tree").setup({
    view = {
        relativenumber = true,
        number = true,
    },
    renderer = { 
        highlight_opened_files = "name",
        icons = {-- To disable the display of icons see |renderer.icons.show|
            show = {
                git = true,
                folder = false,
                file = false,
                folder_arrow = false,
            },
        },
    },
})
local options = {
    filetype = "on", --turned on filetype detection
    foldmethod = "expr",
    foldexpr = "nvim_treesitter#foldexpr()",
    foldnestmax = 1,
    clipboard = vim.opt.clipboard + "unnamedplus" + "unnamed",
    expandtab = true,
    hlsearch = false,
    iskeyword = vim.opt.iskeyword + "-" + "_",
    number = true,
    pumheight = 7,
    relativenumber = true,
    scrolloff = 999,
    shiftwidth = 4, -- Number of spaces to use for each step of (auto)indent
    showmode = false,
    smartindent = true, -- Do smart autoindenting when starting a new line
    softtabstop = 4, -- Number of spaces that a <Tab> counts for while performing editing operations
    tabstop = 4, -- Number of spaces that a <Tab> in the file counts for
    updatetime = 200,
}
for k, v in pairs(options) do
    vim.opt[k] = v
end
```

### Steps to reproduce

just run the config

### Expected behavior

see the name of opened files highlighted

### Actual behavior

nothing happens

**Comment by alex-courtis** [comment] 2022-11-27 23:44
Reproduced with minimal config. Highlight is correctly applied for buffers that are open at the time of opening the tree only.

**Comment by matteouni** [comment] 2022-11-28 03:36
first of all ty for the fast response, but I dont know what you mean by highlighted.  As you can see by the pic, the name of the file opened via Nvim-tree (<C-v>)(test.c) is not highlighted, nor init.lua is highlighted
![highlight](https://user-images.githubusercontent.com/118944004/204188480-1560dc17-f97e-4aaa-a2b6-f2ff5d670e48.png)

**Comment by matteouni** [comment] 2022-11-28 03:37
I've refreshed the window as well, but still no result

**Comment by alex-courtis** [comment] 2022-11-28 05:42
> first of all ty for the fast response, but I dont know what you mean by highlighted.

I was just confirming the reproduction. It will be fixed when time permits.

Highlight in this case refers to the `NvimTreeOpenedFile` highlight group, which applies to `NvimTreeOpenedFile`.

**Comment by alex-courtis** [comment] 2023-01-01 04:38
It looks like we have fixed this one.

@matteouni please update to latest and re-test.

**Comment by alex-courtis** [comment] 2023-01-29 03:56
Assuming fixed.

**Closed by alex-courtis** 2023-01-29 03:56 UTC
Labels: bug, awaiting feedback, reproduced
