### ISSUE TITLE
Error executing vim. schedule lua callback: ...cker/start/nvim-tree. lua/lua/nvim-tree/renderer/init.lua:397

### ISSUE THREAD

**Issue by an1ndra** [nvim-tree/nvim-tree.lua#925] opened 2022-02-02 16:29 UTC
**OS**
Pop os 21.10

**Neovim version**
```shell
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Nvim-tree version**
master branch

**Describe the bug**
Every time I try to open nvim-tree this error show. and no icon, files and folder show. ![Screenshot from 2022-02-02 21-47-25](https://user-images.githubusercontent.com/36324543/152194846-3ddd60a0-fdcf-4706-bce0-95ff3d7e3631.png)

**To Reproduce**
Use any nvim-tree command example `NvimTreeRefresh`, NvimTreeOpen

**Expected behavior**
Nvim Tree should be open without any error

**Comment by yetipowers** [comment] 2022-02-03 10:30
+1 I have exactly the same issue!

**Comment by kyazdani42** [comment] 2022-02-03 12:11
cannot reproduce this, do you have newlines in your filenames ?

**Comment by yetipowers** [comment] 2022-02-03 18:25
The fastest method for reproduction is e.g. just installing lunarvim, I deleted all the configs (from .local/share and .config), and I get the error directly upon start now. Its strange since it only happened since this morning …

```
Error executing vim.schedule lua callback: ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:397: String cannot contain newlines
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:397: in function 'draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:49: in function 'redraw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:28: in function 'callback'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:77: in function 'on_end'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:68: in function 'on_finish'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:77: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

So in line 397 is the following:

```lua
  api.nvim_buf_set_lines(view.View.bufnr, 0, -1, false, lines)
```

[The checkhealth does not even have nvim-tree mentioned and it all seems alright.](https://gist.github.com/yetipowers/a4aaa47520cc0c36839fd098ac792884) 

One strange thing though, is that I can not access any folder for my user (e.g. /home/test/)

But, I can activate and open folders on my usb stick, thats really strange..  I hope a solution can be found, I can (sort of) live with that in the moment, but now I can't navigate on my .config folder  with nvim-tree …

**Comment by yetipowers** [comment] 2022-02-04 19:53
For me it's working again, don't really know what caused the issue. 
It worked since I deleted the compiled file from packer in plugin folder, running `:PackerCompile`, `:PackerSync`, and  `:Packer Update`

It's strange because I had tried it before, but now it works again like a charm!

**Comment by kyazdani42** [comment] 2022-02-05 10:47
might be an issue with the lunarvim config maybe ? i'm not sure. Or maybe conflicting with another plugin.

**Comment by alex-courtis** [comment] 2022-03-26 04:41
@meanindra perhaps you could provide a reproducible test case:

Start with the minimal config as per the bug report template: https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose

Add your nvim-tree config. If you still cannot reproduce, add your plugins and their configuration until you can reproduce.

Post that modified minimal config and we can attempt to reproduce that.

**Comment by zamboney** [comment] 2022-05-17 10:14
I had the same problem and (after i reinstall `neovim` and `nvim-tree`) the issue didn't solve!

finally i figure out the problem. it's seem that i had one file the contain `newline` in it.

so in order to reproduce this issue all you need to do is create a file that contain a `newline` and the error thrown. 

example:

```
touch file$'\n'
```

hope it's will help 😄

**Comment by alex-courtis** [comment] 2022-09-03 03:57
Closing due to inactivity.

**Comment by Oumar-1** [comment] 2023-03-19 03:15
i have the same error but i have fixed by just commenting 
ignore_list at update_focued_file 

i don't why it works but it does 
`	update_focused_file = {
		enable = true,
		update_cwd = true,
		--[[ ignore_list = { "/node_modules" }, ]]
	},
`

**Comment by Samgarr** [comment] 2024-04-22 11:01
Hello, i m also experiencing this issue. I can confirm that crash is cause by newline in file name. In my case, file with newline in name was created by mistake and i am convinced that it should not lead to crash of nvim-tree.

```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Vim:Error executing Lua callback: .../nvim/lazy/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:23: 'replacement string' 
item contains newlines                                                                                                                                                                                               
stack traceback:                                                                                                                                                                                                     
        [C]: in function 'nvim_buf_set_lines'                                                                                                                                                                        
        .../nvim/lazy/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:23: in function '_draw'                                                                                                                          
        .../nvim/lazy/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:59: in function 'draw'                                                                                                                           
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/lib.lua:195: in function 'open_view_and_draw'                                                                                                            
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/lib.lua:259: in function 'open'                                                                                                                          
        ...m/lazy/nvim-tree.lua/lua/nvim-tree/actions/tree/open.lua:32: in function 'open'                                                                                                                           
        ...share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/commands.lua:51: in function <...share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/commands.lua:50>                                                                 
        [C]: in function 'cmd'                                                                                                                                                                                       
        .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>                                                                 
stack traceback:                                                                                                                                                                                                     
        [C]: in function 'cmd'                                                                                                                                                                                       
        .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16> 
```


```
VIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742


nvim-tree: v1.3.0
```

**Comment by alex-courtis** [comment] 2024-04-23 00:41
Replicated with `touch foo$'\n'bar`

**Comment by alex-courtis** [comment] 2024-04-23 02:06
This should be resolved - displaying, opening and renaming files.

I'd be grateful if you tested a fix @Samgarr 

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 925-handle-newlines-in-file-names
```

When you're finished testing:
```sh
git checkout master
```

**Comment by alex-courtis** [comment] 2024-04-28 03:53
@Samgarr I'd be grateful for your testing this, as it's operating system dependent.

**Comment by Samgarr** [comment] 2024-05-01 20:05
Sorry for late response, i didn't notice the notification. I can confirm that the fix works for me.

**Closed** 2024-05-04 03:51 UTC
Labels: bug

**Comment by AlejandroSanchez90** [comment] 2024-10-04 16:07
is this merged ? im having same issue

**Comment by alex-courtis** [comment] 2024-10-05 00:15
The fix has been release.

Please provide a reproducer for your case @AlejandroSanchez90 :a new [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) would be most gratefully appreciated.

**Comment by AlejandroSanchez90** [comment] 2024-10-05 00:49
> The fix has been release.
> 
> Please attempt the trivial test:
> ```sh
> touch foo$'\n'bar
> ```
> 
> Please provide a reproducer for your case @AlejandroSanchez90 :a new [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) would be most gratefully appreciated.

I fixed my issue by adding node module folder to the ignore list for tracked files
