### ISSUE TITLE
Expand or collapse should work on the current node and it's children

### ISSUE THREAD

**Issue by asmodeus812** [nvim-tree/nvim-tree.lua#2446] opened 2023-10-04 16:11 UTC
**Can this functionality be implemented utilising API?**
Not really, the currrent collapse or expand is very primitive and has no direct control over what is expanded or collapsed, the method simply uses explorer.nodes, takes no regard of the current node. 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to collapse or contract the current node, and all it's children, not the entire tree up untill the parent, without taking into account on which node the cursor is

**Describe alternatives you've considered**
Re-implementing the collapse or expand to use node.nodes ? instead of explorer.nodes

**Additional context**
No

**Comment by alex-courtis** [comment] 2023-10-07 03:45
Duplicate of #2119

Let's track it there.

**Closed by alex-courtis** 2023-10-07 03:45 UTC
Labels: feature request
