### ISSUE TITLE
`<Tab>` key no longer toggles directories

### ISSUE THREAD

**Issue by asang24** [nvim-tree/nvim-tree.lua#2097] opened 2023-03-29 05:52 UTC
### Description

Hi, 

when I press Tab key , it don't work,  cannot toggle folders & move in nvim-tree, what's the matter?
plz help this.
Thanks.

### Neovim version

```text
NVIM 0.8.3
```

### Operating system and version

Macos 12.6.3

### nvim-tree version

45400cd

### Minimal config

```lua
all default config
```

### Steps to reproduce

1. open nvim-tree
2. Press Tab key to want to move xxx.lua file
3. can not  work, but j & k key can work

**Comment by gegoune** [comment] 2023-03-29 06:46
`<Tab>` key is mapped to open file without moving to it by default. You can change the key map to whatever you want, if I understood your question correctly.

**Comment by samvdst** [comment] 2023-03-29 15:40
I am experiencing the same problem. I used to be able to use `<Tab>` associated with `Open Preview` to `expand/collapse` directories.

This stopped working today after upgrading to the latest version (I cannot tell which version broke this).

I feel that the `open_preview` function should behave similarly to the `open_or_expand_or_dir_up` function (used on edit).
I get the desired behavior by changing the code in `api.lua`

From
```lua
local function open_preview(node)
  if node.nodes or node.name == ".." then
    return
  end

  edit("preview", node)
end
```
To
```lua
local function open_preview(node)
  if node.name == ".." then
    require("nvim-tree.actions.root.change-dir").fn ".."
  elseif node.nodes then
    require("nvim-tree.lib").expand_or_collapse(node)
    return
  end

  edit("preview", node)
end
```

I don't know how to override this from the config file instead of modifying the source. I'm very new to Lua.

**Comment by gegoune** [comment] 2023-03-29 16:34
@samvdst Thanks for clarifying, it makes sense now.

This is the mapping for Tab as per default returned by `api.config.mappings.default_on_attach()`:
https://github.com/nvim-tree/nvim-tree.lua/blob/45400cd7e02027937cd5e49845545e606ecf5a1f/lua/nvim-tree/keymap.lua#L40

Without looking any deeper it seems to be regression introduced by 74959750. Previously it was mapped to an action, this PR changed it to api call. Action had this:
https://github.com/nvim-tree/nvim-tree.lua/blob/9c97e6449b0b0269bd44e1fd4857184dfa57bb4c/lua/nvim-tree/actions/dispatch.lua#L85C16-L89

which `api.node.open.preview` is missing:
https://github.com/nvim-tree/nvim-tree.lua/blob/45400cd7e02027937cd5e49845545e606ecf5a1f/lua/nvim-tree/api.lua#L132-L138
---
I have opened https://github.com/nvim-tree/nvim-tree.lua/pull/2099/files, which changes what happens on `..` nodes. Perhaps that's undesirable.

**Closed** 2023-04-03 06:20 UTC
Labels: bug, regression
